export enum PropertyCode {
  MASTER_EMAIL = 'MASTER_EMAIL',
  CC_EMAILS = 'CC_EMAILS',
  MID_EVAL_EXP_DATE = 'MID_EVAL_EXP_DATE',
  END_EVAL_EXP_DATE = 'END_EVAL_EXP_DATE',
  TRANS_DATE_TOLERANCE = 'TRANS_DATE_TOLERANCE',
  DEFAULT_DONATION_REASON = 'DEFAULT_DONATION_REASON',
  ACCOUNT_NAME = 'ACCOUNT_NAME',
  ACCOUNT_NUMBER = 'ACCOUNT_NUMBER',
  BANK_NAME = 'BANK_NAME',
  BANK_BRANCH = 'BANK_BRANCH'
}
