export enum PropertyCode {
  MASTER_EMAIL = 'MASTER_EMAIL',
  CC_EMAILS = 'CC_EMAILS',
  MID_EVAL_EXP_DATE = 'MID_EVAL_EXP_DATE',
  END_EVAL_EXP_DATE = 'END_EVAL_EXP_DATE',
  TRANS_DATE_TOLERANCE = 'TRANS_DATE_TOLERANCE'
}
